In [2]:
import torch 

In [3]:
torch.__version__

'2.9.1'

In [9]:
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])

In [10]:
print(type(x))
print(type(y))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [11]:
print(x.shape)
print(y.shape)

torch.Size([1, 2])
torch.Size([2, 1])


In [4]:
zeroes = torch.zeros((3, 4))

In [5]:
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
ones = torch.ones((3, 4))

In [7]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
randoms = torch.randint(low = 0, high = 10, size=(3,4))

In [9]:
randoms

tensor([[7, 0, 6, 9],
        [3, 2, 5, 4],
        [5, 3, 8, 6]])

In [10]:
random_reals = torch.rand(3, 4)

In [11]:
random_reals

tensor([[0.0074, 0.5161, 0.4590, 0.2772],
        [0.3698, 0.8535, 0.9066, 0.6973],
        [0.5068, 0.8368, 0.2631, 0.4616]])

In [14]:
normal_rand = torch.randn((3, 4))

In [15]:
normal_rand

tensor([[ 1.9629,  1.1982,  0.4105,  0.3805],
        [ 0.7775, -0.3933,  0.6674,  0.5596],
        [ 0.6400,  0.0189,  0.0823,  0.8523]])

## Tensor Operations

In [17]:
x = torch.tensor(([1, 2, 3],
                 [4, 5, 6]))

In [19]:
x * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [20]:
x + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [21]:
y = x.add(10)

In [22]:
y

tensor([[11, 12, 13],
        [14, 15, 16]])

In [23]:
y.shape

torch.Size([2, 3])

In [24]:
y.view((3, 2))

tensor([[11, 12],
        [13, 14],
        [15, 16]])

In [28]:
y = y.view((3, 2))

In [29]:
x @ y

tensor([[ 82,  88],
        [199, 214]])

In [30]:
y @ x

tensor([[ 59,  82, 105],
        [ 69,  96, 123],
        [ 79, 110, 141]])

In [31]:
x = torch.tensor([[2., -1.], [1., 1.]], requires_grad=True)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [32]:
out = x.pow(2).sum()

In [33]:
out.backward()

In [34]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])